on: [push]

jobs:
    test_pull_request_job:
        runs-on: ubuntu-latest
        name: A test for my pull-request-action
        steps:
            - name: Do the thing
              id: action
              uses: ./.github/actions/create-pull-request-action
              with:
                head: dev
                base: release
            - name: Read PR ID
              run: echo "The Pull Request ID was: ${{ steps.action.outputs.pull-request-id }}"
            - name: Read Created
              run: if [ "${{ steps.action.outpus.created }}" == "True" ]; then echo "We created the PR!"; else echo "We did not create the PR :("; fi

